# generated by make process
# .clang-format
# .travis.yml
# CHANGELOG.md
# LICENSE
# README.md
# appveyor.yml
# configure.bat
# tests/cppcheck-1.81/noExplicitConstructor.cpp
# tests/msvc2017-2/a.cpp
# tests/msvc2017-2/pch.cpp
# tests/msvc2017-2/pch.h
# tests/msvc2017-3/a.cpp
# tests/msvc2017-4/a.cpp
# tests/msvc2017-5/a.cpp
# tests/msvc2017/c4102.cpp
