# generated by make process
# .clang-format
# .travis.yml
# CHANGELOG.md
# LICENSE
# README.md
# appveyor.yml
# configure.bat
# tests/cppcheck-1.81/noExplicitConstructor.cpp
# tests/msvc2017/c4102.cpp
